# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Users\24352\Desktop\src\毕设\personal-ai-assistant\frontend\ui_design\untitled.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.setWindowModality(QtCore.Qt.NonModal)
        Form.resize(860, 522)
        Form.setMinimumSize(QtCore.QSize(860, 522))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("./frontend/assets/第24帧.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        Form.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(800, 500))
        self.tabWidget.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tabWidget.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.tabWidget.setAcceptDrops(False)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setStyleSheet("/* 整个 QTabWidget 的样式 */\n"
"QTabWidget {\n"
"    background-color: transparent; /* 背景完全透明 */\n"
"    border: none; /* 没有边框 */\n"
"}\n"
"\n"
"/* QTabBar 的样式 */\n"
"QTabBar {\n"
"    background-color: transparent; /* 背景完全透明 */\n"
"    border: none; /* 没有边框 */\n"
"}\n"
"\n"
"/* 单个标签页的样式 */\n"
"QTabBar::tab {\n"
"    background-color: transparent; /* 背景完全透明 */\n"
"    border: none; /* 没有边框 */\n"
"    padding: 4px; /* 内边距，可以根据需要调整 */\n"
"}\n"
"\n"
"/* 选中标签页的样式 */\n"
"QTabBar::tab:selected {\n"
"    background-color: transparent; /* 选中时背景依然透明 */\n"
"    border: none; /* 没有边框 */\n"
"}\n"
"\n"
"/* 鼠标悬停时的样式 */\n"
"QTabBar::tab:hover,QTabBar::tab:pressed {\n"
"    padding-left: 8px;\n"
"    padding-bottom: 8px;\n"
"    background-color: rgba(0, 0, 0, 0.1); /* 轻微的半透明背景，可选 */\n"
"}\n"
"")
        self.tabWidget.setTabPosition(QtWidgets.QTabWidget.West)
        self.tabWidget.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.tabWidget.setIconSize(QtCore.QSize(28, 28))
        self.tabWidget.setElideMode(QtCore.Qt.ElideLeft)
        self.tabWidget.setDocumentMode(False)
        self.tabWidget.setTabsClosable(False)
        self.tabWidget.setMovable(False)
        self.tabWidget.setTabBarAutoHide(False)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_1 = QtWidgets.QWidget()
        self.tab_1.setMinimumSize(QtCore.QSize(800, 500))
        self.tab_1.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tab_1.setStyleSheet("background-color: transparent; /* 背景完全透明 */\n"
"")
        self.tab_1.setObjectName("tab_1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.tab_1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.QueryWidget = HighlightableListWidget(self.tab_1)
        self.QueryWidget.setStyleSheet("")
        self.QueryWidget.setMovement(QtWidgets.QListView.Static)
        self.QueryWidget.setFlow(QtWidgets.QListView.TopToBottom)
        self.QueryWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.QueryWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.QueryWidget.setObjectName("QueryWidget")
        self.verticalLayout_2.addWidget(self.QueryWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(38, 36, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.searchOptions = QtWidgets.QComboBox(self.tab_1)
        self.searchOptions.setStyleSheet("QComboBox {\n"
"    border: 1px solid black; /* 黑色边框 */\n"
"    background-color: rgb(255, 255, 255);\n"
"    color: rgb(0, 0, 0);\n"
"}\n"
"")
        self.searchOptions.setObjectName("searchOptions")
        self.searchOptions.addItem("")
        self.searchOptions.addItem("")
        self.searchOptions.addItem("")
        self.searchOptions.addItem("")
        self.searchOptions.addItem("")
        self.horizontalLayout.addWidget(self.searchOptions)
        self.searchInput = QtWidgets.QLineEdit(self.tab_1)
        self.searchInput.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #838383; /* 黑色边框 */\n"
"    border-radius: 14px; /* 圆角 */\n"
"    padding: 5px; /* 内边距 */\n"
"}\n"
"\n"
"/* 输入框获得焦点时的样式 */\n"
"/* QLineEdit:focus {\n"
"    border: 2px solid #0078D7; /* 获得焦点时边框颜色变化，例如深蓝色 */\n"
"/* }")
        self.searchInput.setObjectName("searchInput")
        self.horizontalLayout.addWidget(self.searchInput)
        self.searchQuery = QtWidgets.QPushButton(self.tab_1)
        self.searchQuery.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* 背景完全透明 */\n"
"    border: none; /* 没有边框 */\n"
"    padding: 3px;\n"
"    border-radius: 15px;\n"
"}\n"
"/* 鼠标悬停时的样式 */\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.1); /* 轻微的半透明背景 */\n"
"}\n"
"\n"
"/* 按下时的样式 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.2); /* 稍微明显一点的半透明背景 */\n"
"}")
        self.searchQuery.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/搜索.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon1.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/搜索_b.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.searchQuery.setIcon(icon1)
        self.searchQuery.setIconSize(QtCore.QSize(30, 30))
        self.searchQuery.setObjectName("searchQuery")
        self.horizontalLayout.addWidget(self.searchQuery)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 12)
        self.horizontalLayout.setStretch(3, 1)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tabWidget.addTab(self.tab_1, icon1, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.new_conversation = QtWidgets.QPushButton(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.new_conversation.sizePolicy().hasHeightForWidth())
        self.new_conversation.setSizePolicy(sizePolicy)
        self.new_conversation.setObjectName("new_conversation")
        self.gridLayout_3.addWidget(self.new_conversation, 1, 0, 1, 1)
        self.chatinput = QtWidgets.QLineEdit(self.tab_2)
        self.chatinput.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #838383; /* 黑色边框 */\n"
"    border-radius: 14px; /* 圆角 */\n"
"    padding: 5px; /* 内边距 */\n"
"}\n"
"\n"
"/* 输入框获得焦点时的样式 */\n"
"/* QLineEdit:focus {\n"
"    border: 2px solid #0078D7; /* 获得焦点时边框颜色变化，例如深蓝色 */\n"
"/* }")
        self.chatinput.setObjectName("chatinput")
        self.gridLayout_3.addWidget(self.chatinput, 1, 1, 1, 1)
        self.send = QtWidgets.QPushButton(self.tab_2)
        self.send.setStyleSheet("QPushButton {\n"
"    background-color: transparent; /* 背景完全透明 */\n"
"    border: none; /* 没有边框 */\n"
"    padding: 3px;\n"
"    border-radius: 15px;\n"
"}\n"
"/* 鼠标悬停时的样式 */\n"
"QPushButton:hover {\n"
"    background-color: rgba(0, 0, 0, 0.1); /* 轻微的半透明背景 */\n"
"}\n"
"\n"
"/* 按下时的样式 */\n"
"QPushButton:pressed {\n"
"    background-color: rgba(0, 0, 0, 0.2); /* 稍微明显一点的半透明背景 */\n"
"}")
        self.send.setText("")
        self.send.setIcon(icon1)
        self.send.setIconSize(QtCore.QSize(30, 30))
        self.send.setObjectName("send")
        self.gridLayout_3.addWidget(self.send, 1, 2, 1, 1)
        self.dialogue = MessageListWidget(self.tab_2)
        self.dialogue.setObjectName("dialogue")
        self.gridLayout_3.addWidget(self.dialogue, 0, 1, 1, 2)
        self.messagelist = QtWidgets.QListWidget(self.tab_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.messagelist.sizePolicy().hasHeightForWidth())
        self.messagelist.setSizePolicy(sizePolicy)
        self.messagelist.setMaximumSize(QtCore.QSize(120, 16777215))
        self.messagelist.setSizeIncrement(QtCore.QSize(0, 0))
        self.messagelist.setStyleSheet("")
        self.messagelist.setObjectName("messagelist")
        self.gridLayout_3.addWidget(self.messagelist, 0, 0, 1, 1)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/AI.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon2.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/AI-B.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_2, icon2, "")
        self.Note = QtWidgets.QWidget()
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Note.sizePolicy().hasHeightForWidth())
        self.Note.setSizePolicy(sizePolicy)
        self.Note.setObjectName("Note")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.Note)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.noteList = QtWidgets.QListWidget(self.Note)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.noteList.sizePolicy().hasHeightForWidth())
        self.noteList.setSizePolicy(sizePolicy)
        self.noteList.setMinimumSize(QtCore.QSize(120, 0))
        self.noteList.setObjectName("noteList")
        self.verticalLayout_3.addWidget(self.noteList)
        self.newNote = QtWidgets.QPushButton(self.Note)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.newNote.sizePolicy().hasHeightForWidth())
        self.newNote.setSizePolicy(sizePolicy)
        self.newNote.setObjectName("newNote")
        self.verticalLayout_3.addWidget(self.newNote)
        self.horizontalLayout_8.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_2 = QtWidgets.QLabel(self.Note)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_7.addWidget(self.label_2)
        self.titleEdit = QtWidgets.QLineEdit(self.Note)
        self.titleEdit.setReadOnly(True)
        self.titleEdit.setObjectName("titleEdit")
        self.horizontalLayout_7.addWidget(self.titleEdit)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.label = QtWidgets.QLabel(self.Note)
        self.label.setObjectName("label")
        self.horizontalLayout_7.addWidget(self.label)
        self.tagsEdit = QtWidgets.QLineEdit(self.Note)
        self.tagsEdit.setReadOnly(True)
        self.tagsEdit.setObjectName("tagsEdit")
        self.horizontalLayout_7.addWidget(self.tagsEdit)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.noteShow = QtWidgets.QTextEdit(self.Note)
        self.noteShow.setReadOnly(True)
        self.noteShow.setObjectName("noteShow")
        self.verticalLayout_4.addWidget(self.noteShow)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.editNote = QtWidgets.QPushButton(self.Note)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.editNote.sizePolicy().hasHeightForWidth())
        self.editNote.setSizePolicy(sizePolicy)
        self.editNote.setObjectName("editNote")
        self.horizontalLayout_6.addWidget(self.editNote)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem3)
        self.saveNote = QtWidgets.QPushButton(self.Note)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveNote.sizePolicy().hasHeightForWidth())
        self.saveNote.setSizePolicy(sizePolicy)
        self.saveNote.setObjectName("saveNote")
        self.horizontalLayout_6.addWidget(self.saveNote)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem4)
        self.delNote = QtWidgets.QPushButton(self.Note)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.delNote.sizePolicy().hasHeightForWidth())
        self.delNote.setSizePolicy(sizePolicy)
        self.delNote.setObjectName("delNote")
        self.horizontalLayout_6.addWidget(self.delNote)
        self.verticalLayout_4.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8.addLayout(self.verticalLayout_4)
        self.horizontalLayout_8.setStretch(0, 1)
        self.horizontalLayout_8.setStretch(1, 5)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/笔记本、笔记.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon3.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/笔记本-b.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.Note, icon3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_4)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.radioButton = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton.setChecked(True)
        self.radioButton.setObjectName("radioButton")
        self.horizontalLayout_2.addWidget(self.radioButton)
        self.radioButton_2 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_2.setObjectName("radioButton_2")
        self.horizontalLayout_2.addWidget(self.radioButton_2)
        self.radioButton_3 = QtWidgets.QRadioButton(self.tab_4)
        self.radioButton_3.setObjectName("radioButton_3")
        self.horizontalLayout_2.addWidget(self.radioButton_3)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_4)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.listWidget = QtWidgets.QListWidget(self.tab_4)
        self.listWidget.setStyleSheet("QListWidget {\n"
"    background-color: #f0f4f8; /* 背景颜色，选择了一个淡蓝色 */\n"
"    border: 1px solid #cdd6de; /* 边框颜色和宽度，淡灰色边框 */\n"
"    border-radius: 5px; /* 边框圆角半径 */\n"
"    padding: 5px; /* 内边距 */\n"
"    font-family: \"Segoe UI\", \"Helvetica Neue\", Arial, sans-serif; /* 字体 */\n"
"    font-size: 14px; /* 字体大小 */\n"
"    outline:0px; \n"
"}\n"
"\n"
"QListWidget::item {\n"
"    padding: 5px; /* 列表项内边距 */\n"
"    margin-bottom: 2px; /* 每个列表项之间的间距 */\n"
"    color: #333333; /* 文字颜色，深灰色 */\n"
"}\n"
"\n"
"QListWidget::item:hover {\n"
"    background-color: #e1e7ed; /* 鼠标悬停时背景颜色，淡灰色 */\n"
"    color: #000000; /* 鼠标悬停时文字颜色，黑色 */\n"
"    border-radius: 5px; /* 圆角半径 */\n"
"}\n"
"\n"
"QListWidget::item:selected {\n"
"    background-color: #bcd9e1; /* 选中项背景颜色，淡蓝绿色 */\n"
"    color: #000000; /* 选中项文字颜色，黑色 */\n"
"    border-radius: 5px; /* 圆角半径 */\n"
"}")
        self.listWidget.setViewMode(QtWidgets.QListView.ListMode)
        self.listWidget.setBatchSize(100)
        self.listWidget.setObjectName("listWidget")
        self.verticalLayout_5.addWidget(self.listWidget)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/数据库.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon4.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/数据库_b.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon4.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/数据库.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_4, icon4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/待办事项.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon5.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/待办事项_b.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        icon5.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/待办事项.png"), QtGui.QIcon.Disabled, QtGui.QIcon.Off)
        self.tabWidget.addTab(self.tab_5, icon5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/设置.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        icon6.addPixmap(QtGui.QPixmap(".\\frontend\\ui_design\\../assets/设置_b.png"), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.tabWidget.addTab(self.tab_6, icon6, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.QueryWidget, self.searchInput)
        Form.setTabOrder(self.searchInput, self.searchQuery)
        Form.setTabOrder(self.searchQuery, self.searchOptions)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "AI助手亚托莉"))
        self.QueryWidget.setSortingEnabled(False)
        self.searchOptions.setItemText(0, _translate("Form", "全部"))
        self.searchOptions.setItemText(1, _translate("Form", "对话"))
        self.searchOptions.setItemText(2, _translate("Form", "笔记"))
        self.searchOptions.setItemText(3, _translate("Form", "知识库"))
        self.searchOptions.setItemText(4, _translate("Form", "待办"))
        self.searchInput.setPlaceholderText(_translate("Form", "输入关键词"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_1), _translate("Form", "搜索"))
        self.new_conversation.setText(_translate("Form", "新建对话"))
        self.chatinput.setPlaceholderText(_translate("Form", "在此发送消息"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_2), _translate("Form", "AI问答"))
        self.newNote.setText(_translate("Form", "新建"))
        self.label_2.setText(_translate("Form", "Title:"))
        self.label.setText(_translate("Form", "Tags"))
        self.editNote.setText(_translate("Form", "切换到编辑"))
        self.saveNote.setText(_translate("Form", "保存"))
        self.delNote.setText(_translate("Form", "删除"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.Note), _translate("Form", "笔记"))
        self.radioButton.setText(_translate("Form", "全部"))
        self.radioButton_2.setText(_translate("Form", "文档"))
        self.radioButton_3.setText(_translate("Form", "笔记"))
        self.pushButton_2.setText(_translate("Form", "上传"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_4), _translate("Form", "知识库"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_5), _translate("Form", "待办事项"))
        self.tabWidget.setTabToolTip(self.tabWidget.indexOf(self.tab_6), _translate("Form", "设置"))
from frontend.src.components.Query_list import HighlightableListWidget
from frontend.src.components.chat_message import MessageListWidget
